export const NOTE_CREATE_REQUEST= 'NOTE_CREATE_REQUEST'
export const NOTE_CREATE_SUCCESS='NOTE_CREATE_SUCCESS'
export const NOTE_CREATE_FAIL='NOTE_CREATE_FAIL'

export const NOTES_LIST_REQUEST= 'NOTES_LIST_REQUEST'
export const NOTES_LIST_SUCCESS='NOTES_LIST_SUCCESS'
export const NOTES_LIST_FAIL='NOTES_LIST_FAIL'




export const NOTES_UPDATE_REQUEST= 'NOTES_UPDATE_REQUEST'
export const NOTES_UPDATE_SUCCESS= 'NOTES_UPDATE_SUCCESS'
export const NOTES_UPDATE_FAIL= 'NOTES_UPDATE_FAIL'

export const NOTES_REMOVE_SUCCESS='NOTES_REMOVE_SUCCESS'